### ISSUE TITLE
[1.0beta] client.fetchNextPage() gives TypeError

### ISSUE THREAD

**Issue by danielpost** [Shopify/js-buy-sdk#433]
I am trying to use `fetchNextPage()` to get the next page of products, but getting the following error:

```
TypeError: Cannot read property 'shop' of undefined
    at index.js:1998
    at Array.reduce (<anonymous>)
    at index.js:1997
    at <anonymous>
```

This is line 1997-1999 that is being referred to:
```js
response.model = path.reduce(function (object, key) {
    return object[key];
}, response.model);
```

Here is my (reduced) use case:
```js
const firstProduct = await client.product.fetchAll(1)
const secondProduct = await client.fetchNextPage(firstProduct)
```

`firstProduct` works fine, but `secondProduct` gives the TypeError.

Apologies if this is caused by my own mistake, I'm not 100% sure if I'm using the function correctly, and couldn't figure out what was causing the error based on the source code.

**Comment by minasmart** [comment]
Yep. this is an underlying issue in the graphql client. It's generating a next page query, but not actually re-declaring any of the variables used in the initial query. should have a fix out shortly.

**Comment by danielpost** [comment]
@minasmart awesome, thank you! If there is anything I can do to help please let me know.

**Comment by danielpost** [comment]
I hate to say it, but I'm getting the exact same error after upgrading:
```
TypeError: Cannot read property 'shop' of undefined
    at index.js:2017
    at Array.reduce (<anonymous>)
    at index.js:2016
    at <anonymous>
```

Is there anything I need to do besides upgrading that would solve it?

**Comment by minasmart** [comment]
I'm not able to reproduce this locally. Are you able to paste the errors hash that's returned from the request in your browsers network panel?

**Comment by danielpost** [comment]
Can you elaborate on how to do that? This is the response from the graphql query:

```
{
  "errors": [
    {
      "message": "Fragment ProductFragment was used, but not defined",
      "locations": [
        {
          "line": 1,
          "column": 267
        }
      ],
      "fields": [
        "query",
        "shop",
        "products",
        "edges",
        "node",
        "... ProductFragment"
      ]
    },
    {
      "message": "Variable $query is used by  but not declared",
      "locations": [
        {
          "line": 1,
          "column": 70
        }
      ],
      "fields": [
        "query",
        "shop",
        "products",
        "query"
      ]
    },
    {
      "message": "Variable $sortKey is used by  but not declared",
      "locations": [
        {
          "line": 1,
          "column": 86
        }
      ],
      "fields": [
        "query",
        "shop",
        "products",
        "sortKey"
      ]
    },
    {
      "message": "Variable $reverse is used by  but not declared",
      "locations": [
        {
          "line": 1,
          "column": 104
        }
      ],
      "fields": [
        "query",
        "shop",
        "products",
        "reverse"
      ]
    }
  ]
}
```

**Comment by minasmart** [comment]
The above is exactly what I needed. I think I tested this is too much isolation. I've found the issue. Should have another fix out shortly.

**Comment by blakewatson** [comment]
Yep same issue, except I'm getting` Cannot read property 'node' of undefined`.

**Comment by minasmart** [comment]
As I said above: working on a fix.

**Comment by minasmart** [comment]
This should all be resolved in `v1.0.0-beta.4` which is being deployed in the next few minutes. Unfortunately, the graphql compiler and client both had issues that weren't persisting enough state across generated pagination queries. It all appears to be fixed now.

**Comment by DanWebb** [comment]
@minasmart Thanks for this, I'm seeing new pages of products pulling in now which is great but there seems to still be an issue with where the response is returned in "fetchNextPage".

The error I'm seeing the error "Uncaught (in promise) TypeError: Cannot read property 'products' of undefined"

I've traced this back to the following part of the "fetchNextPage" method:
```
      return this.send(query, variableValues).then(function (response) {
        response.model = path.reduce(function (object, key) {
          console.log(object, key);
          return object[key];
        }, response.model);

        return response;
      });
```
I added the `console.log` there to debug and it sends an output like this...

<img width="1398" alt="screen shot 2017-11-03 at 16 30 57" src="https://user-images.githubusercontent.com/5038459/32367359-6ef4f642-c0b4-11e7-9d95-8fbc9b253082.png">

If I output `path` it gives me this array:
```
["node", "products", "node", "products", "node", "products", "node", "products", "node", "products", "node", "products", "node", "products", "node", "products", "node", "products"]
```
I don't have enough underlying knowledge to know if this is the fix or it's going to cause other issues down the line but if the path array is made unique i.e. `["node", "products"]` then the response gets through and I can access the products using `nextPageOfProducts.model`.

In case the further context is helpful there's some info on how I'm running the code on issue #440

**Comment by minasmart** [comment]
ok. I know what I did wrong here. I think there's a variable scoping issue. I'll get this fixed this week. Thanks for finding these issues.

**Comment by minasmart** [comment]
@DanWebb, fixed in https://github.com/Shopify/graphql-js-client/pull/101.

Will go out in `beta.5` of this library.

**Comment by minasmart** [comment]
`v1.0.0-beta.5` is released, and includes the fix for this.

**Comment by psamsotha** [comment]
There still seems to be a problem (I'm using 1.0.2). The first call to `this.client.fetchNextPage(products);` seems to be ok. But with the next call, I am still seeing the same error 

```javascript
TypeError: Cannot read property 'shop' of undefined
    at index.js:2073
    at Array.reduce (<anonymous>)
    at index.js:2072
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4629)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
   ...
```

The following code reproduces the problem. I am not sure if the size I used (5) has anything to do with the problem, but I do not have enough products to test the default size of 20.

```javascript
this.client = buildClient(config);
this.client.product.fetchAll(5).then((products1) => {
  console.log(products1);
  this.client.fetchNextPage(products1).then((results) => {
    let products2 = results.model;
    console.log(products2);
    this.client.fetchNextPage(products2).then((results) => {
      // never reaches here. Throws above error
      let products3 = results.model;
      console.log(products3);
    });
  });
});
```

Or am I just not using this correctly?

**Comment by ajeeshadressary** [comment]
I am following this url  https://shopify.github.io/js-buy-sdk/

My code is :

import Client from 'shopify-buy';
const client = Client.buildClient({
    domain: 'xxxxx.myshopify.com',
    storefrontAccessToken: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  });

// Fetch all products in your shop
client.product.fetchAll().then((products) => {
  // Do something with the products
  console.log(products);
});

**But i am getting an error: Cannot read property 'shop' of undefined issue exists.**

**Comment by rizedr** [comment]
@minasmart I am still getting error in `v1.2.0` with products fetched from a collection:
1. `client.collection.fetchWithProducts(id) => products` works, got 20 products
2. `client.fetchNextPage(products) => products` works, got 40 products
3. `client.fetchNextPage(products) => products` works, got 60 products
4. `client.fetchNextPage(products) => error` doesn't work anymore.
```
Uncaught (in promise) TypeError: Cannot read property 'node' of undefined
    at index.js:2073
    at Array.reduce (<anonymous>)
    at index.js:2072
    at <anonymous>
```

I think this issue should be reopened.

**Comment by minasmart** [comment]
I can’t reproduce this error locally. Are there any other details you can provide?

**Comment by rizedr** [comment]
@minasmart I've made `create-react-app` to demonstrate the issue. A deployed version is available to be seen here: http://shopify-next-page-bug.surge.sh/

Here is a repo that you can clone and reproduce the error locally: https://github.com/rizedr/shopify-fetchNextPage

Let me know if I can provide you more info.

**Comment by lisadreamer** [comment]
@minasmart Hi! I have similar issue. First time when I call fetchNextPage and pass previous products, it works fine. and i receive "nextPageOfProducts" which has data and model. (data has shop and then products with edges and pageInfo)

Im just new to these can u explain what should I pass into fetchNextPage next?if i pass for next call nextPageOfProducts.model (which seems having needed products to pass) it would give me an error: Cannot read property 'shop' of undefined. Apparently response.model in the fetchNextPage is undefined this time. maybe i pass wrong products?

**Comment by rizedr** [comment]
@lisadreamer you should pass the list of products.

Opened a new issue #493 for the problem I've described.

**Comment by lisadreamer** [comment]
@rizedr ofc i pass list of products. when i pass to fetchNextPage list of products received from fetchAll or fetchQuery it works. but when i pass next time to fetchNextPage list of products received from fecthNextPage it gives an error.

**Comment by rizedr** [comment]
@lisadreamer are you passing the whole list of products `[...initialProducts, ...nextProducts]`? Or just the `nextProducts`? You need to pass the whole list.

**Comment by lisadreamer** [comment]
@rizedr i tried whole list, same error. "Cannot read property 'shop' of undefined".
in side of fetchNextPage() : 

this.send(query, variableValues).then(function (response) {
        response.model = path.reduce(function (object, key) {
          return object[key];
        }, response.model);
return response;
});

where path = ["shop", "products"] and response.model is undefined 
=> shop of undefined

**Comment by rizedr** [comment]
@lisadreamer yeap, that is the issue that I've opened here: #493 for this version.
